### ISSUE TITLE
can't initialise a jsonify instance

### ISSUE THREAD

**Issue by zhaoyi0113** [wankdanker/node-redis-jsonify#7]
Below is my source code:

```
const redis = require('redis');
const jsonify = require('redis-jsonify');
const client = redis.createClient(dbConfig);
return jsonify(client);
```
I got below exception error:

```

/Users/joey/dev/TheWebServer/node_modules/redis-jsonify/index.js:21
            lastArgType = typeof args[args.length - 1];
                                           ^
TypeError: Cannot read property 'length' of undefined
    at RedisClient.RedisJSONify.redis.internal_send_command.redis.send_command (/Users/joey/dev/TheWebServer/node_modules/redis-jsonify/index.js:21:44)
    at RedisClient.info (/Users/joey/dev/node_modules/redis/lib/individualCommands.js:169:17)
    at RedisClient.ready_check (/Users/joey/dev/node_modules/redis/index.js:534:10)
    at RedisClient.on_connect (/Users/joey/dev/node_modules/redis/index.js:428:14)
    at Socket.<anonymous> (/Users/joey/dev/node_modules/redis/index.js:268:14)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1169:10)
```

I am using versions:

```
"redis-jsonify": "^1.0.1"
"redis": "^2.8.0",
```

My node version is `v8.9.1`.

**Comment by amit-mn** [comment]
I am also facing this issue.

**Comment by Shijith260193** [comment]
Same here. I tried to jsonify the redis client to avoid the response as [Object Object] and i get the same issue. 

` "redis-jsonify": "^1.0.1" , "redis": "^2.8.0" `

My nodejs version is  v8.9.0
